name: devops
anchor: feet
default_height: 0.9276
flippable: true
poses:
  general:
    head_anchor:
    - 0.4869
    - 0.5315
    mouth_offset:
    - 0.4869
    - 0.5109
  angry:
    head_anchor:
    - 0.4869
    - 0.5315
    mouth_offset:
    - 0.4869
    - 0.5109
  rire:
    head_anchor:
    - 0.4869
    - 0.5315
    mouth_offset:
    - 0.4869
    - 0.5109
  surprise:
    head_anchor:
    - 0.4869
    - 0.5315
    mouth_offset:
    - 0.4869
    - 0.5109
expressions: []
